[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"
authors = ["Lutz MitlÃ¤nder <lutz@mitlaender.dev>"]

[dependencies]
geo = "0.32.0"
good_lp = { version = "1.14.2", default-features = false, features = ["microlp", "highs"] }
num = "0.4.3"
regex = "1.12.2"
